[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	bblanchon/ArduinoJson@^7.0.0
build_flags = -DWIFI_SSID='"wifi_ssid"' -DWIFI_PASSWORD='"wifi_password"'

